# Generated by Django 5.0.7 on 2024-07-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('Elderly Homes', 'Elderly Homes'), ('Hospitals & Clinics', 'Hospitals & Clinics'), ("Children's Homes", "Children's Homes")], default="Children's Homes", max_length=25),
            preserve_default=False,
        ),
    ]
