# Generated by Django 5.0.7 on 2024-07-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='hours',
        ),
    ]
