# Generated by Django 5.0.7 on 2024-07-16 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userevent_date_remove_userevent_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
