# Generated by Django 5.0.2 on 2024-07-23 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_volunteerhours'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteeringRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255)),
                ('event', models.CharField(max_length=255)),
                ('donations', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hours', models.PositiveIntegerField()),
            ],
        ),
    ]
