# Generated by Django 5.0.7 on 2024-07-24 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_volunteeringrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerhours',
            old_name='date',
            new_name='date_from',
        ),
        migrations.AddField(
            model_name='volunteerhours',
            name='date_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
