# Generated by Django 5.0.7 on 2024-07-24 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_volunteerhours_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhours',
            name='date_from',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='date_to',
            field=models.DateTimeField(),
        ),
    ]
