# Generated by Django 5.0.7 on 2024-07-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_volunteerhours_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerhours',
            name='hours',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
