# Generated by Django 5.0.7 on 2024-07-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_volunteerhours_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='type',
        ),
    ]
