# Generated by Django 5.0.7 on 2024-07-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_donation_funds_raised_alter_donation_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='funds_raised',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='supporters',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
