# Generated by Django 5.0.7 on 2024-07-25 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_donation_deadline_alter_donation_funds_raised_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='image',
            field=models.ImageField(default=0, upload_to='donations/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='volunteerhours',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
