# Generated by Django 5.0.7 on 2024-07-30 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_donation_image_alter_volunteerhours_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdonation',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
