# Generated by Django 5.0.7 on 2024-07-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_userdonation_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerhours',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
